server.port=8080
spring.application.name=intermediate-order-lab
spring.datasource.url=jdbc:h2:mem:orderdb
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
